-- MySQL Script generated by MySQL Workbench
-- Sat Jul  3 19:29:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema devgocl_tori
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `devgocl_tori` ;

-- -----------------------------------------------------
-- Schema devgocl_tori
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `devgocl_tori` DEFAULT CHARACTER SET utf8 ;
USE `devgocl_tori` ;

-- -----------------------------------------------------
-- Table `devgocl_tori`.`actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`actividades` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`actividades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(12) NOT NULL,
  `giro` TEXT NULL DEFAULT NULL,
  `actividadEconomica` TEXT NULL DEFAULT NULL,
  `codigoActividadEconomica` INT(11) NULL DEFAULT NULL,
  `actividadPrincipal` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`rut`),
  INDEX `id` (`id` ASC, `rut` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`afp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`afp` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`afp` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `tasa_afp` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`anticipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`anticipos` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`anticipos` (
  `id` INT(11) NOT NULL,
  `trabajador` VARCHAR(12) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `total` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`area` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`area` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`trabajadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`trabajadores` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`trabajadores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(12) NULL,
  `nombres` VARCHAR(450) NULL DEFAULT NULL,
  `apellidos` VARCHAR(450) NULL DEFAULT NULL,
  `fecha_ingreso` DATE NULL DEFAULT NULL,
  `nacionalidad` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `estado_civil` INT(11) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(600) NULL DEFAULT NULL,
  `telefono` INT(11) NULL DEFAULT NULL,
  `direccion` TEXT NULL DEFAULT NULL,
  `cargo` TEXT NULL DEFAULT NULL,
  `tipo_salud` INT(11) NULL DEFAULT NULL,
  `isapre` INT(11) NULL DEFAULT NULL,
  `sueldo` INT(11) NULL DEFAULT NULL,
  `afp` INT(11) NULL DEFAULT NULL,
  `tipo_contrato` INT(11) NULL DEFAULT NULL,
  `carga_familiar` INT(11) NULL DEFAULT NULL,
  `contrato_indefinido` INT(11) NULL DEFAULT NULL,
  `duracion_contrato` INT(11) NULL DEFAULT NULL,
  `mostrar` INT(11) NULL DEFAULT NULL,
  `finiquitado` INT(11) NULL DEFAULT NULL,
  `numero_cargas` INT(11) NULL DEFAULT NULL,
  `area` INT(11) NULL DEFAULT NULL,
  `modalidad_trabajo` INT(11) NULL DEFAULT NULL,
  `trabaja_hora_extras` INT(11) NULL DEFAULT NULL,
  `fecha_pacto` DATE NULL DEFAULT NULL,
  `sexo` VARCHAR(2) NULL DEFAULT NULL,
  `uf_plan` DOUBLE NULL DEFAULT NULL,
  `movilizacion` INT(11) NULL DEFAULT NULL,
  `colacion` INT(11) NULL DEFAULT NULL,
  INDEX `id` (`id` ASC, `rut` ASC),
  INDEX `fk_afp_idx` (`afp` ASC),
  INDEX `fk_area_idx` (`area` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_afp`
    FOREIGN KEY (`afp`)
    REFERENCES `devgocl_tori`.`afp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_area`
    FOREIGN KEY (`area`)
    REFERENCES `devgocl_tori`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`ausencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`ausencias` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`ausencias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `trabajador` VARCHAR(12) NULL DEFAULT NULL,
  `motivo` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC, `trabajador` ASC),
  INDEX `fk_t2323dsa_idx` (`trabajador` ASC),
  CONSTRAINT `fk_t2323dsa`
    FOREIGN KEY (`trabajador`)
    REFERENCES `devgocl_tori`.`trabajadores` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`caja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`caja` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`caja` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_caja` INT(11) NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `fecha_cierre` DATETIME NULL DEFAULT NULL,
  `monto_inicial` INT(11) NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  `vendedor` VARCHAR(500) NULL DEFAULT NULL,
  `turno` INT(11) NULL DEFAULT '0',
  `monto_entrega` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`numero_caja`),
  INDEX `id` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`calendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`calendario` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`calendario` (
  `id` INT(11) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL,
  `titulo` VARCHAR(450) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`categorias` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`categorias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(255) NULL DEFAULT 'nd.jpg',
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` INT(11) NULL DEFAULT NULL COMMENT '0:productos\\n1:ingrediente\\n2:promociones\\n3: menus',
  `estado` INT(11) NULL DEFAULT '1',
  `delivery` INT(11) NULL DEFAULT NULL,
  `orden` INT(11) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC, `nombre` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`clientes` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`clientes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(25) NOT NULL,
  `rut` VARCHAR(12) NULL DEFAULT NULL,
  `razonSocial` TEXT NULL DEFAULT NULL,
  `email` TEXT NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `mostrar` INT(11) NULL DEFAULT '0',
  `comuna` INT(11) NULL DEFAULT NULL,
  `credito_utilizado` INT(11) NULL DEFAULT NULL,
  `cdgSIISucur` INT(11) NULL DEFAULT NULL,
  `giro` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`telefono`),
  INDEX `id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`colaciones_trabajadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`colaciones_trabajadores` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`colaciones_trabajadores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `hora` TIME NULL DEFAULT NULL,
  `id_trabajador` INT NULL DEFAULT NULL,
  `dia` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC, `id_trabajador` ASC),
  INDEX `fk_t223232asdas_idx` (`id_trabajador` ASC),
  CONSTRAINT `fk_t223232asdas`
    FOREIGN KEY (`id_trabajador`)
    REFERENCES `devgocl_tori`.`trabajadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 115
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`proveedores` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`proveedores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(12) NOT NULL,
  `nombres` VARCHAR(100) NULL DEFAULT NULL,
  `apellidos` VARCHAR(100) NULL DEFAULT NULL,
  `giro` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `es_empresa` INT(11) NULL DEFAULT NULL,
  `mostrar` INT(11) NULL DEFAULT '0',
  `credito_utilizado` INT(11) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`rut`),
  INDEX `id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`compras` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`compras` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `fecha_pago` DATETIME NULL DEFAULT NULL,
  `numero_compra` INT(11) NOT NULL,
  `numero_pago` INT(11) NULL DEFAULT NULL,
  `rut` VARCHAR(12) NULL DEFAULT NULL,
  `total` INT(11) NULL DEFAULT NULL,
  `nombre_archivo` VARCHAR(500) NULL DEFAULT NULL,
  `saldo_pendiente` INT(11) NULL DEFAULT NULL,
  `pagado` INT(11) NULL DEFAULT NULL,
  `tipo_pago` VARCHAR(45) NULL DEFAULT NULL,
  `documento` VARCHAR(45) NULL DEFAULT NULL,
  `numero_documento` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`numero_compra`),
  INDEX `id` (`id` ASC, `numero_pago` ASC, `rut` ASC),
  INDEX `FK_ruuu_idx` (`rut` ASC),
  CONSTRAINT `FK_ruuu`
    FOREIGN KEY (`rut`)
    REFERENCES `devgocl_tori`.`proveedores` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`comunas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`comunas` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`comunas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `comuna` VARCHAR(64) NULL DEFAULT NULL,
  `provincia_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 348
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`contactos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`contactos` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`contactos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(25) NULL DEFAULT NULL,
  `nombres` VARCHAR(100) NULL DEFAULT NULL,
  `correo` VARCHAR(200) NULL DEFAULT NULL,
  `tipo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC, `telefono` ASC),
  INDEX `fk_cccc_idx` (`telefono` ASC),
  CONSTRAINT `fk_cccc`
    FOREIGN KEY (`telefono`)
    REFERENCES `devgocl_tori`.`clientes` (`telefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`detalle_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`detalle_compras` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`detalle_compras` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `numero_compra` INT(11) NULL DEFAULT NULL,
  `insumo` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` INT(11) NULL DEFAULT NULL,
  `cantidad` DOUBLE NULL DEFAULT NULL,
  `precio_compra` INT(11) NULL DEFAULT NULL,
  `descuento` DOUBLE NULL DEFAULT NULL,
  `flete` INT(11) NULL DEFAULT NULL,
  `adicional` INT(11) NULL DEFAULT NULL,
  `medida_compra` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC),
  INDEX `fk_c_idx` (`numero_compra` ASC),
  CONSTRAINT `fk_c`
    FOREIGN KEY (`numero_compra`)
    REFERENCES `devgocl_tori`.`compras` (`numero_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`detalle_egresos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`detalle_egresos` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`detalle_egresos` (
  `id` INT(11) NOT NULL,
  `numero_egreso` INT(11) NULL DEFAULT NULL,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  `cantidad` DOUBLE NULL DEFAULT NULL,
  `motivo` TEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`detalle_inventarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`detalle_inventarios` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`detalle_inventarios` (
  `id` INT(11) NOT NULL,
  `numero_inventario` INT(11) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `cantidad` DOUBLE NULL DEFAULT NULL,
  `unidades` INT(11) NULL DEFAULT NULL,
  `paquetes` INT(11) NULL DEFAULT NULL,
  `total_pulgadas` DOUBLE NULL DEFAULT NULL,
  `medida` DOUBLE NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`detalle_pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`detalle_pagos` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`detalle_pagos` (
  `id` INT(11) NOT NULL,
  `numero_compra` INT(11) NULL DEFAULT NULL,
  `numero_venta` INT(11) NULL DEFAULT NULL,
  `numero_pago` INT(11) NULL DEFAULT NULL,
  `total` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`detalle_pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`detalle_pedidos` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`detalle_pedidos` (
  `id` INT(11) NOT NULL,
  `numero_pedido` INT(11) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` DOUBLE NULL DEFAULT NULL,
  `valor_unitario` INT(11) NULL DEFAULT NULL,
  `total_pulgadas` DOUBLE NULL DEFAULT NULL,
  `cantidad_por_retirar` DOUBLE NULL DEFAULT NULL,
  `tipo_venta` INT(11) NULL DEFAULT NULL,
  `cantidad_devolucion` DOUBLE NULL DEFAULT NULL,
  `despachado` INT(11) NULL DEFAULT NULL,
  `tipo_servicio` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`ingredientes` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`ingredientes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `precio` INT(11) NULL DEFAULT NULL,
  `categoria` INT(11) NULL DEFAULT '0',
  `stock` DOUBLE NULL DEFAULT '0',
  `stock_minimo` DOUBLE NULL DEFAULT '0',
  `medida` VARCHAR(10) NULL DEFAULT '0',
  `mostrar` INT(11) NULL DEFAULT '0',
  `para_venta` INT(11) NULL DEFAULT '0',
  `precio_venta` INT(11) NULL DEFAULT NULL,
  `gramos_venta` DOUBLE NULL DEFAULT '0',
  `unidad_compra` DOUBLE NOT NULL DEFAULT '0',
  `cantida_unidad_compra` DOUBLE NOT NULL DEFAULT '0',
  `medida_equivalencia` VARCHAR(11) NOT NULL DEFAULT '0',
  `lugar_venta` INT(11) NULL DEFAULT '0',
  `abreviatura` VARCHAR(100) NULL DEFAULT '-',
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  `porcentaje_merma` DOUBLE NULL DEFAULT NULL,
  `delivery` INT(11) NULL DEFAULT NULL COMMENT '0: no\\n1: si',
  `precio_venta_insumo_delivery` INT(11) NULL DEFAULT NULL,
  `gramo_insumo_venta_delivery` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC, `categoria` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`paquete_ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`paquete_ingredientes` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`paquete_ingredientes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_paquete_ingrediente` INT(11) NULL DEFAULT NULL,
  `nombre` VARCHAR(450) NULL DEFAULT NULL,
  `repetible` VARCHAR(4) NULL DEFAULT NULL COMMENT '0: no\\n1 :si',
  `obligatorio` VARCHAR(4) NULL DEFAULT NULL COMMENT '0: no\\n1 :si',
  `minimo` DOUBLE NULL DEFAULT NULL,
  `maximo` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`detalle_paquete_ingrediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`detalle_paquete_ingrediente` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`detalle_paquete_ingrediente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_paquete_ingrediente` INT(11) NULL DEFAULT NULL,
  `ingrediente` INT(11) NULL DEFAULT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC, `numero_paquete_ingrediente` ASC, `ingrediente` ASC),
  INDEX `fk_di_idx` (`ingrediente` ASC),
  INDEX `fk_dp_idx` (`numero_paquete_ingrediente` ASC),
  CONSTRAINT `fk_di`
    FOREIGN KEY (`ingrediente`)
    REFERENCES `devgocl_tori`.`ingredientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dp`
    FOREIGN KEY (`numero_paquete_ingrediente`)
    REFERENCES `devgocl_tori`.`paquete_ingredientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`productos` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`productos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_producto` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `barra` INT(11) NULL DEFAULT '0',
  `stock` INT(11) NULL DEFAULT NULL,
  `precio_venta` INT(11) NULL DEFAULT NULL,
  `margen` DOUBLE NULL DEFAULT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT 'nd.jpg',
  `categoria` INT(11) NULL DEFAULT NULL,
  `informacion` TEXT NULL DEFAULT NULL,
  `mostrar` INT(11) NULL DEFAULT '1',
  `promo_bebestible` INT(11) NULL DEFAULT '0',
  `promo_comida` INT(11) NULL DEFAULT '0',
  `tipo_cocina` INT(11) NULL DEFAULT '0',
  `es_happy` INT(11) NULL DEFAULT NULL,
  `hora_inicio_hh` TIME NULL DEFAULT NULL,
  `hora_termino_hh` TIME NULL DEFAULT '00:00:00',
  `precio_venta_hh` INT(11) NULL DEFAULT '0',
  `codigo_producto` VARCHAR(45) NOT NULL,
  `para_delivery` INT(11) NULL DEFAULT NULL COMMENT '0: NO \\n1: SI',
  `mostrar_pagina` VARCHAR(45) NULL DEFAULT NULL COMMENT '0: NO \\n1: SI\\n',
  PRIMARY KEY (`numero_producto`, `codigo_producto`),
  INDEX `id` (`id` ASC, `categoria` ASC, `numero_producto` ASC, `codigo_producto` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`detalle_ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`detalle_ventas` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`detalle_ventas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `numero_venta` INT(11) NULL DEFAULT '0',
  `numero_comprobante` INT(11) NULL DEFAULT NULL,
  `producto` INT(11) NULL DEFAULT '0',
  `cantidad` DOUBLE NULL DEFAULT '0',
  `precio` INT(11) NULL DEFAULT '0',
  `total` INT(11) NULL DEFAULT '0',
  `nuevo_pedido` INT(11) NULL DEFAULT '0',
  `estado_despacho` INT(11) NULL DEFAULT '1',
  `mensaje` INT(11) NULL DEFAULT '1',
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prodddddcs_idx` (`producto` ASC),
  INDEX `id` (`numero_comprobante` ASC, `numero_venta` ASC, `id` ASC),
  CONSTRAINT `fk_prodddddcs`
    FOREIGN KEY (`producto`)
    REFERENCES `devgocl_tori`.`productos` (`numero_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`direcciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`direcciones` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`direcciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(25) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC, `telefono` ASC),
  INDEX `fk_c33_idx` (`telefono` ASC),
  CONSTRAINT `fk_c33`
    FOREIGN KEY (`telefono`)
    REFERENCES `devgocl_tori`.`clientes` (`telefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`documentos_trabajadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`documentos_trabajadores` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`documentos_trabajadores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(450) NULL DEFAULT NULL,
  `tipo` VARCHAR(255) NULL DEFAULT NULL,
  `trabajador` VARCHAR(12) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC, `trabajador` ASC),
  INDEX `fk_t333_idx` (`trabajador` ASC),
  CONSTRAINT `fk_t333`
    FOREIGN KEY (`trabajador`)
    REFERENCES `devgocl_tori`.`trabajadores` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`egresos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`egresos` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`egresos` (
  `id` INT(11) NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `numero_egreso` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`empresa` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`empresa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(12) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `giro` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `ciudad` VARCHAR(100) NULL DEFAULT NULL,
  `numero_producto` INT(11) NULL DEFAULT '1',
  `numero_venta` INT(11) NULL DEFAULT '1',
  `numero_caja` INT(11) NULL DEFAULT '1',
  `numero_cotizacion` INT(11) NULL DEFAULT '1',
  `numero_comprobante` INT(11) NULL DEFAULT '1',
  `numero_compra` INT(11) NULL DEFAULT '1',
  `numero_egreso` INT(11) NULL DEFAULT '1',
  `numero_pago` INT(11) NULL DEFAULT '1',
  `numero_devolucion` INT(11) NULL DEFAULT '1',
  `numero_combinacion` INT(11) NULL DEFAULT NULL,
  `iva` INT(11) NULL DEFAULT '19',
  `clave_autorizacion` INT(11) NULL DEFAULT '2580',
  `tipo` INT(11) NULL DEFAULT '0',
  `tipo_sistema` INT(11) NOT NULL DEFAULT '0' COMMENT '0 : restaurantes\\n1 : mini market \\n2 : punto de venta\\n',
  `impresion_barra` INT(11) NULL DEFAULT NULL,
  `impresion_cocina` INT(11) NULL DEFAULT NULL,
  `impresion_venta` INT(11) NULL DEFAULT NULL,
  `impresion_precuenta` INT(11) NULL DEFAULT NULL,
  `logo` VARCHAR(450) NULL DEFAULT NULL,
  `delivery` INT(11) NULL DEFAULT NULL,
  `propina` INT(11) NULL DEFAULT NULL,
  `impresora_red` INT(11) NULL DEFAULT NULL COMMENT '0: red\\n1: usb\\n',
  `ip_impresora` VARCHAR(100) NULL DEFAULT NULL,
  `nombre_impresora` VARCHAR(45) NULL DEFAULT NULL,
  `key` VARCHAR(450) NULL DEFAULT NULL,
  `estandar_chef` INT(11) NULL DEFAULT NULL,
  `hora_inicio` TIME NULL DEFAULT NULL,
  `hora_termino` TIME NULL DEFAULT NULL,
  `intervalo` INT(11) NULL DEFAULT NULL,
  `numero_paquete_ingrediente` INT NULL,
  PRIMARY KEY (`rut`),
  INDEX `id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`eventos` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`eventos` (
  `id` INT(11) NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `rut_cliente` VARCHAR(12) NULL DEFAULT NULL,
  `rut_vendedor` VARCHAR(12) NULL DEFAULT NULL,
  `tipo` VARCHAR(20) NULL DEFAULT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`gastos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`gastos` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`gastos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `numero_gasto` INT(11) NOT NULL,
  `tipo_pago` VARCHAR(45) NULL DEFAULT NULL,
  `numero_documento` INT(11) NULL DEFAULT NULL,
  `total` INT(11) NULL DEFAULT NULL,
  `rut` VARCHAR(12) NULL DEFAULT NULL,
  `dinero_caja` INT(11) NULL DEFAULT NULL,
  `total_caja` INT(11) NULL DEFAULT NULL,
  `obs` TEXT NULL DEFAULT NULL,
  `documento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`numero_gasto`),
  INDEX `id` (`id` ASC, `rut` ASC),
  INDEX `fk_rut_idx` (`rut` ASC),
  CONSTRAINT `fk_rut`
    FOREIGN KEY (`rut`)
    REFERENCES `devgocl_tori`.`proveedores` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`horario_trabajadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`horario_trabajadores` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`horario_trabajadores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `trabajador` INT NULL DEFAULT NULL,
  `dia` INT(11) NULL DEFAULT NULL,
  `hora_inicio` TIME NULL DEFAULT NULL,
  `hora_termino` TIME NULL DEFAULT NULL,
  `colacion` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC, `trabajador` ASC),
  INDEX `fk_t44343_idx` (`trabajador` ASC),
  CONSTRAINT `fk_t44343`
    FOREIGN KEY (`trabajador`)
    REFERENCES `devgocl_tori`.`trabajadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`horas_extras_trabajadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`horas_extras_trabajadores` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`horas_extras_trabajadores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `hora` TIME NULL DEFAULT NULL,
  `trabajador` VARCHAR(12) NULL DEFAULT NULL,
  `dia` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC, `trabajador` ASC),
  INDEX `fk_t2_idx` (`trabajador` ASC),
  CONSTRAINT `fk_t20`
    FOREIGN KEY (`trabajador`)
    REFERENCES `devgocl_tori`.`trabajadores` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`isapres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`isapres` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`isapres` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`keys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`keys` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`keys` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `key` VARCHAR(45) NULL DEFAULT NULL,
  `level` INT(2) NULL DEFAULT NULL,
  `ignore_limits` TINYINT(1) NULL DEFAULT NULL,
  `is_private_key` TINYINT(1) NULL DEFAULT NULL,
  `ip_addresses` TEXT NULL DEFAULT NULL,
  `date_created` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`licencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`licencias` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`licencias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_termino` DATE NULL DEFAULT NULL,
  `id_trabajador` INT NULL DEFAULT NULL,
  `numero_licencia` VARCHAR(35) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC, `id_trabajador` ASC),
  INDEX `fk_v_idx` (`id_trabajador` ASC),
  CONSTRAINT `fk_v0`
    FOREIGN KEY (`id_trabajador`)
    REFERENCES `devgocl_tori`.`trabajadores` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`logs` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `responsable` VARCHAR(12) NULL DEFAULT NULL,
  `ip` VARCHAR(45) NULL DEFAULT NULL,
  `producto_eliminado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_log_r_idx` (`responsable` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`mesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`mesas` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`mesas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  `mostrar` INT(11) NULL DEFAULT NULL,
  `nivel` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`nacionalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`nacionalidad` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`nacionalidad` (
  `PAIS_NAC` VARCHAR(45) NOT NULL,
  `GENTILICIO_NAC` VARCHAR(45) NULL DEFAULT NULL,
  `ISO_NAC` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PAIS_NAC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`pagos` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`pagos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `numero_pago` INT(11) NOT NULL,
  `tipo_pago` VARCHAR(45) NULL DEFAULT NULL,
  `dinero_recibido` INT(11) NULL DEFAULT NULL,
  `deuda_final` INT(11) NULL DEFAULT NULL,
  `rut` VARCHAR(12) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`numero_pago`),
  INDEX `id` (`id` ASC, `rut` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`provincias` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`provincias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `provincia` VARCHAR(64) NULL DEFAULT NULL,
  `region_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 57
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`regiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`regiones` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`regiones` (
  `id` INT(11) NOT NULL,
  `region` VARCHAR(64) NULL DEFAULT NULL,
  `abreviatura` VARCHAR(4) NULL DEFAULT NULL,
  `capital` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`turnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`turnos` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`turnos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_trabajador` INT NULL DEFAULT NULL,
  `semana` VARCHAR(45) NULL DEFAULT NULL,
  `opcion_trabajador` VARCHAR(4) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `id_area` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC, `id_trabajador` ASC, `id_area` ASC),
  INDEX `fk_trabaj_idx` (`id_trabajador` ASC),
  INDEX `fk_Area_idx` (`id_area` ASC),
  CONSTRAINT `fk_trabaj`
    FOREIGN KEY (`id_trabajador`)
    REFERENCES `devgocl_tori`.`trabajadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Area`
    FOREIGN KEY (`id_area`)
    REFERENCES `devgocl_tori`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(300) NOT NULL,
  `clave` VARCHAR(255) NULL DEFAULT NULL,
  `rango` INT(11) NULL DEFAULT NULL,
  `nombres` VARCHAR(50) NULL DEFAULT NULL,
  `apellidos` VARCHAR(50) NULL DEFAULT NULL,
  `mostrar` INT(11) NULL DEFAULT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `ultimo_login` DATETIME NULL DEFAULT NULL,
  `expiracion_login` DATETIME NULL DEFAULT NULL,
  `conectado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`correo`),
  INDEX `id` (`id` ASC, `correo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`vacaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`vacaciones` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`vacaciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_termino` DATE NULL DEFAULT NULL,
  `trabajador` VARCHAR(12) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC, `trabajador` ASC),
  INDEX `fk_v_idx` (`trabajador` ASC),
  CONSTRAINT `fk_v`
    FOREIGN KEY (`trabajador`)
    REFERENCES `devgocl_tori`.`trabajadores` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `devgocl_tori`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devgocl_tori`.`ventas` ;

CREATE TABLE IF NOT EXISTS `devgocl_tori`.`ventas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_venta` INT(11) NULL DEFAULT '0',
  `numero_comprobante` INT(11) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_pago` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dinero_recibido` INT(11) NULL DEFAULT NULL,
  `vuelto` INT(11) NULL DEFAULT NULL,
  `total` INT(11) NULL DEFAULT NULL,
  `propina` INT(11) NULL DEFAULT NULL,
  `documento` VARCHAR(45) NULL DEFAULT NULL,
  `cliente` VARCHAR(25) NULL DEFAULT NULL,
  `garzon` VARCHAR(500) NULL DEFAULT NULL,
  `pagado` INT(11) NULL DEFAULT '0',
  `saldo_pendiente` INT(11) NULL DEFAULT NULL,
  `mesas` VARCHAR(45) NULL DEFAULT NULL,
  `comensales` INT(11) NULL DEFAULT '1',
  `descuento` INT(11) NULL DEFAULT NULL,
  `descripcion_descuento` TEXT NULL DEFAULT NULL,
  `estado_despacho` INT(11) NULL DEFAULT '0',
  `mensaje_cocina` INT(11) UNSIGNED NULL DEFAULT '0',
  `nombre_cliente` VARCHAR(200) NULL DEFAULT '-',
  `mensaje_entrada` INT(11) NULL DEFAULT '0',
  `numero_operacion` INT(11) NULL DEFAULT NULL,
  `observacion_general` TEXT NULL DEFAULT NULL,
  `direccion_cliente` TEXT NULL DEFAULT NULL,
  `delivery` INT(11) NULL DEFAULT NULL,
  `numero_boleta_electronica` INT(11) NULL DEFAULT NULL,
  `tipo_delivery` INT(11) NULL DEFAULT NULL,
  `hora_delivery` TIME NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id` (`numero_comprobante` ASC, `numero_venta` ASC, `garzon` ASC, `cliente` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `devgocl_tori` ;

-- -----------------------------------------------------
-- procedure CrearTurnosArea
-- -----------------------------------------------------

USE `devgocl_tori`;
DROP procedure IF EXISTS `devgocl_tori`.`CrearTurnosArea`;

DELIMITER $$
USE `devgocl_tori`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `CrearTurnosArea`(IN `_area` INT, IN `_semana` VARCHAR(45), IN `_trabajador` VARCHAR(12))
BEGIN
				  DECLARE valor_id INT;
				
				  DECLARE cantidad_trabajadores_area INT;
				  DECLARE _hora_inicio TIME;
				  DECLARE _hora_termino TIME;
                  DECLARE _dia INT;
                  DECLARE i INT;
                  DECLARE _fecha DATE;
              
				DECLARE _trabajador_bd VARCHAR(12);
               
				DECLARE cursor_trabajadores CURSOR FOR 
								SELECT * FROM trabajadores WHERE rut = _trabajador;
				DECLARE cursor_horario_trabajadores CURSOR FOR
								SELECT hora_inicio,hora_termino,trabajador,dia FROM horario_trabajadores WHERE trabajador = _trabajador;
				DECLARE cursor_colaciones_trabajadores CURSOR FOR
								SELECT * FROM colaciones_trabajadores WHERE trabajador = _trabajador;
				DECLARE cursor_horas_extras_trabajadores CURSOR FOR 
								SELECT * FROM horas_extras_trabajadores WHERE trabajador = _trabajador;
                DECLARE cursor_turnos_trabajador CURSOR FOR 
								SELECT * FROM turnos WHERE trabajador = _trabajador AND dia = _dia AND semana = _semana;                
					SELECT COUNT(*) INTO @cantidad_trabajadores_area FROM trabajadores WHERE area = _area;
                
                SET valor_id = 1;
             
                SET i = 1;
			
				-- Condición de salida
				
				 
              OPEN cursor_horario_trabajadores;
						WHILE i <= @cantidad_trabajadores_area DO
								FETCH cursor_horario_trabajadores INTO _hora_inicio, _hora_termino,_trabajador_bd,_dia;
								 
                                  
                                  WHILE (_hora_inicio <= _hora_termino) DO
											IF(_hora_inicio <= _hora_termino) THEN
													INSERT INTO turnos (dia,hora,trabajador,opcion_trabajador,semana,valor_id,fecha) VALUES(_dia,_hora_inicio,_trabajador,'T',_semana,valor_id,"2021-06-18");
													SET _hora_inicio = ADDTIME(_hora_inicio, "00:30");
													SET _hora_termino = ADDTIME(_hora_termino, "00:30");
                                            END IF;
                               									
								END WHILE;
							SET @i = @i + 1;
                            SET @valor_id = @valor_id + 1;
						END WHILE;
				
				CLOSE cursor_horario_trabajadores;
    END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
